---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "Changing neighborhoods, shifting connections: mapping relational geographies of gentrification using social media data."
```

# Changing neighborhoods, shifting connections: mapping relational geographies of gentrification using social media data

This repository contains the data and code for our paper "Changing neighborhoods, shifting connections: mapping relational geographies of gentrification using social media data". The structure of this folder has been created with [rrtools](https://github.com/benmarwick/rrtools). This version is anonymized for peer review.

## Contents

This repository contains all the data and code needed to reproduce the
results and figures in our paper.

  - [analysis/01-prepare-twitter-data.Rmd](analysis/01-prepare-twitter-data.md):
    Prepare the Twitter data for subsequent analysis. Because of Twitter's terms and condition, we cannot share the raw Twitter data. However, all aggregated data necessary for reproducing the work in this paper is included.
  - [analysis/02-figures.Rmd](analysis/02-figures.md):
    This contains all the analytical and visualization steps needed to reproduce each figure in our analysis.

## How to run

This research compendium has been developed using the statistical programming
language R. To work with the compendium, you will need
installed on your computer the [R software](https://cloud.r-project.org/)
itself and optionally [RStudio Desktop](https://rstudio.com/products/rstudio/download/).
